---
  cpu_freq:
    range:
      - '800000'
      - '900000'
      - '1100000'
      - '1200000'
      - '1400000'
      - '1500000'
      - '1700000'
      - '1800000'
      - '2000000'
      - '2100000'
      - '2400000'
      - '2600000'
      - '2700000'
      - '2900000'
    default: '800000'
  dropout_rate:
    range:
            #      - '0.3'
      - '0.4'
        #- '0.5'
        #- '0.6'
        #- '0.7'
        #- '0.8'
    default: '0.4'
#    min: 0.4
#    max: 0.8
#    default: 0.4
  learn_rate:
#    min: 0.000001
#    max: 0.001
#    default: 0.001
    range:
            # - '0.01'
            # - '0.03'
            #- '0.05'
      - '0.001'
        #- '0.003'
        #- '0.009'
    default: '0.001'

  batch_size:
#    min: 16
#    max: 128
#    default: 32
    range:
            # - '16'
      - '32'
        # - '64'
        # - '96'
        #- '128'
#      - '256'
    default: '32'
  inter_op:
    range:
      - '1'
        # - '2'
        #- '3'
        # - '4'
    default: '1'
  intra_op:
    range:
      - '14'
        # - '21'
        # - '28'
        # - '35'
        #- '42'
        # - '49'
        # - '56'
    default: '14'
