---
  swappiness:
    file: /proc/sys/vm/swappiness
    min: 0
    max: 100
    default: 60
   # bucket_num: 7
    # float: yes # enable this to allow it to be non-int
  dirty_ratio:
    file: /proc/sys/vm/dirty_ratio
    min: 10
    max: 100
    default: 20
    bucket_num: 6
  dirty_background_ratio:
    file: /proc/sys/vm/dirty_background_ratio
    min: 0
    max: 100
    default: 10
  dirty_writeback_centisecs:
    file: /proc/sys/vm/dirty_writeback_centisecs
    min: 100
    max: 1000
    default: 500
    #  overcommit_memory:
    #file: /proc/sys/vm/overcommit_memory
    # min: 0
    #max: 2
    #default: 0
  overcommit_ratio:
    file: /proc/sys/vm/overcommit_ratio
    min: 0
    max: 100
    default: 50
  dirty_expire_centisecs:
    file: /proc/sys/vm/dirty_expire_centisecs
    min: 100
    max: 10000
    default: 3000
  vfs_cache_pressure:
      file: /proc/sys/vm/vfs_cache_pressure
      min: 50
      max: 150
      default: 100
  max_map_count:
      file: /proc/sys/vm/max_map_count
      min: 32765
      max: 98295
      default: 65530

  nr_requests:
    file: /sys/block/sda/queue/nr_requests
    min: 64
    max: 256
    default: 128
  read_ahead_kb:
    file: /sys/block/sda/queue/read_ahead_kb
    min: 64
    max: 512
    default: 128
    bucket_num: 56
  rq_affinity:
      file: /sys/block/sda/queue/rq_affinity
      min: 1
      max: 2
      default: 1

#  tcp_max_syn_backlog:
#    file: /proc/sys/net/ipv4/tcp_max_syn_backlog
#    min: 128
#    max: 4096
#    default: 1024
#  netdev_max_backlog:
#    file: /proc/sys/net/core/netdev_max_backlog
#    min: 100
#    max: 5000
#    default: 1000
#  tcp_slow_start_after_idle:
#     file: /proc/sys/net/ipv4/tcp_slow_start_after_idle
#     min: 0
#     max: 1
#     default: 1
#  somaxconn:
#    file: /proc/sys/net/core/somaxconn
#    min: 128
#    max: 4096
#    default: 128
#  tcp_abort_on_overflow:
#      file: /proc/sys/net/ipv4/tcp_abort_on_overflow
#      min: 0
#      max: 1
#      default: 0
#  tcp_tw_reuse:
#      file: /proc/sys/net/ipv4/tcp_tw_reuse
#      min: 0
#      max: 1
#      default: 0
